version: '3'
services:
  notebook:
    image: robotlocomotion/drake:latest
    command: "jupyter notebook --notebook-dir=/home/notebooks --ip='0.0.0.0' --port=8888 --no-browser --allow-root"
    volumes:
      - '.:/home/notebooks'
    ports:
      - "8888:8888"